filter:
    excluded_paths: [tests/*]
checks:
    php:
        code_rating: true

build:
    tests:
        override:
            command: "php -v"

tools:
    external_code_coverage:
        timeout: 600
        runs: 2
    php_analyzer: true
    php_code_coverage: false
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
